build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  #aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  #armhf: "ghcr.io/home-assistant/armhf-base:3.20"
  #armv7: "ghcr.io/home-assistant/armv7-base:3.20"
  #i386: "ghcr.io/home-assistant/i386-base:3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Ebusd"
  org.opencontainers.image.description: "This Add-on runs eBUSd, a daemon for handling communication with eBUS devices"
  org.opencontainers.image.source: "https://github.com/p.gasidlo/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
